### ISSUE TITLE
Bug in computing critical values in example code

### ISSUE THREAD

**Issue by crafkin** [labordynamicsinstitute/ssb-example-code#1]
I believe there is a bug in the code that generates a critical value. 

`gen criticalvalue95 = invttail(df,0.05)` in the [non-raking example](https://github.com/labordynamicsinstitute/ssb-example-code/blob/master/applications/Stata/lifecycle-earnings/available-case/analysis_noraking.do) (and perhaps elsewhere) gives a critical value for a one-sided t-test. For example, if you plug in df large, Stata reports `criticalvalue95 = 1.645`, which is the critical value for a one-sided 95% CI or a two-sided 90% CI (since the student's t distribution tends to the Normal distribution).  

I don't think the author intended to employ a one-sided test, because when the code considers the GSF case (where adjusting the critical value is not needed), the code uses 1.96 as the critical value for the 95% CI (from the standard normal). 

To fix this, I think the code should read: 
`gen criticalvalue95 = invttail(df,0.025)`. Similarly, for the other critical values, the last number needs to be divided by 2.

**Comment by etotty** [comment]
Fixed.
